### ISSUE TITLE
Python Modules Conflict

### ISSUE THREAD

**Issue by ngbien83** [RichardErkhov/FastFaceSwap#2]
Conflict occurs on both Python 3.8 and Python 3.10 environment:
ERROR: tensorflow-gpu 2.10.1 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 3.20.2 which is incompatible.
ERROR: tensorboard 2.10.1 has requirement protobuf<3.20,>=3.9.2, but you'll have protobuf 3.20.2 which is incompatible.
ERROR: tb-nightly 2.14.0a20230716 has requirement google-auth-oauthlib<1.1,>=0.5, but you'll have google-auth-oauthlib 0.4.6 which is incompatible.
ERROR: tb-nightly 2.14.0a20230716 has requirement tensorboard-data-server<0.8.0,>=0.7.0, but you'll have tensorboard-data-server 0.6.1 which is incompatible.

**Comment by RichardErkhov** [comment]
ignore it, use python 3.10

**Comment by RichardErkhov** [comment]
with normal versions for some reason tensorflow is not working, so I have to use incompatible versions xD
