### ISSUE TITLE
Collab fail  returned non-zero exit status 1.

### ISSUE THREAD

**Issue by G-force78** [RichardErkhov/FastFaceSwap#3]
Traceback (most recent call last):
  File "/content/FastFaceSwap/main.py", line 734, in <module>
    main()
  File "/content/FastFaceSwap/main.py", line 710, in main
    add_audio_from_video(name, args['target_path'], args['output'])
  File "/content/FastFaceSwap/utils.py", line 146, in add_audio_from_video
    subprocess.run(ffmpeg_cmd, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-i', 'Bazdata.mp4_temp.mp4', '-i', '/content/FastFaceSwap/baz.mp4', '-c:v', 'copy', '-map', '0:v:0', '-map', '1:a:0', '-shortest', 'Bazdata.mp4']' returned non-zero exit status 1.

**Comment by RichardErkhov** [comment]
if it's possible I would ask for full output from the program, but based from what I see you don't have audio in your video or something went wrong while copying audio from video

**Comment by RichardErkhov** [comment]
still, Bazdata.mp4_temp.mp4 is the video without the sound, so you can just download it if you don't have the sound in the original video
